# Generated by Django 2.1.3 on 2018-11-20 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseOnTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text_responce', models.CharField(max_length=200, verbose_name='Введение')),
                ('responce_text', models.TextField(max_length=2000, verbose_name='Текст ответа')),
                ('time_responce', models.DateTimeField(auto_now_add=True)),
                ('status_task', models.CharField(choices=[('red', 'не готово'), ('yellow', 'необходима проверка'), ('green', 'готово')], default=('yellow', 'необходима проверка'), max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_text', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('task_text', models.TextField(max_length=2000, verbose_name='Текст задания')),
                ('status', models.CharField(choices=[('red', 'не готово'), ('yellow', 'необходима проверка'), ('green', 'готово')], default=('red', 'не готово'), max_length=256, verbose_name='Статус выполнения')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Work_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='authors_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rasp.Work_category', verbose_name='Категория задания'),
        ),
        migrations.AddField(
            model_name='task',
            name='authors_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя исполнителя'),
        ),
        migrations.AddField(
            model_name='responseontask',
            name='responce_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rasp.Task', verbose_name='Задание для ответа'),
        ),
        migrations.AddField(
            model_name='responseontask',
            name='user_responce',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
