# Generated by Django 2.1.3 on 2019-01-05 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0003_auto_20181125_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseontask',
            name='user_responce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
