# Generated by Django 2.1.3 on 2019-01-08 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0004_auto_20190105_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='authors_name',
            field=models.CharField(max_length=200, verbose_name='Имя исполнителя'),
        ),
    ]
