# Generated by Django 2.1.3 on 2019-01-08 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rasp', '0005_auto_20190108_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseontask',
            name='user_responce',
            field=models.CharField(max_length=200, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='task',
            name='authors_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Имя исполнителя'),
        ),
    ]
